version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - git clone --depth=1 https://github.com/tfutils/tfenv.git ~/.tfenv
      - ln -s ~/.tfenv/bin/* /usr/local/bin
      - tfenv --version
      - export TFENV_AUTO_INSTALL="true"
      - echo $TFENV_AUTO_INSTALL

  pre_build:
    commands:
      - aws configure --profile kmc-${BUILD_ENV} set region "ap-northeast-1"
      - aws configure list
      # - terraform --version
      - git branch -a
      - git checkout ${BRANCH_NAME}
  build:
    commands:
      - bash ./codebuild/terraform_detector/build.sh
      #- bash ./terraform/modules/change-detector-terraform/build.sh
  post_build:
    commands:
